In [45]:
import csv
from jobspy import scrape_jobs

jobs = scrape_jobs(
    # site_name=["indeed", "linkedin", "zip_recruiter", "glassdoor"],
    site_name=["linkedin", "glassdoor"],
    search_term="Data Engineer",
    location="Vietnam",
    results_wanted=20,
    hours_old=336, # (only Linkedin/Indeed is hour specific, others round up to days old)
    country_indeed='Canada',  # only needed for indeed / glassdoor
    
    # linkedin_fetch_description=True # get full description , direct job url , company industry and job level (seniority level) for linkedin (slower)
    # proxies=["208.195.175.46:65095", "208.195.175.45:65095", "localhost"],
    
)
print(f"Found {len(jobs)} jobs")
display(jobs)
# jobs.to_csv("jobs.csv", quoting=csv.QUOTE_NONNUMERIC, escapechar="\\", index=False) # to_excel

2024-08-26 16:07:14,057 - JobSpy - INFO - LinkedIn search page: 1
2024-08-26 16:07:15,257 - JobSpy - INFO - Glassdoor search page: 1
2024-08-26 16:07:17,442 - JobSpy - INFO - Glassdoor finished scraping
2024-08-26 16:07:21,820 - JobSpy - INFO - LinkedIn search page: 2
2024-08-26 16:07:27,420 - JobSpy - INFO - LinkedIn search page: 3
2024-08-26 16:07:27,991 - JobSpy - INFO - Linkedin finished scraping

Found 40 jobs

,id,site,job_url,job_url_direct,title,company,location,job_type,date_posted,salary_source,...,company_url,company_url_direct,company_addresses,company_num_employees,company_revenue,company_description,logo_photo_url,banner_photo_url,ceo_name,ceo_photo_url
0,1009419798820,glassdoor,https://www.glassdoor.ca/job-listing/j?jl=1009...,None,Fresher Test Engineer (QA/QC/Tester),KMS Technology,NaN,None,2024-08-26,None,...,NaN,None,None,None,None,None,None,None,None,None
10,1009417936285,glassdoor,https://www.glassdoor.ca/job-listing/j?jl=1009...,None,"Reliability Engineer, Pixel Hardware",Google,NaN,None,2024-08-24,None,...,NaN,None,None,None,None,None,None,None,None,None
18,1009417907882,glassdoor,https://www.glassdoor.ca/job-listing/j?jl=1009...,None,"Data Scientist Ai Engineer, Ml Engineer",Deliveree On-Demand Logistics (Southeast Asia),NaN,None,2024-08-24,None,...,NaN,None,None,None,None,None,None,None,None,None
2,1009417683588,glassdoor,https://www.glassdoor.ca/job-listing/j?jl=1009...,None,Data Engineer,VNG,NaN,None,2024-08-23,None,...,NaN,None,None,None,None,None,None,None,None,None
9,1009417275759,glassdoor,https://www.glassdoor.ca/job-listing/j?jl=1009...,None,"Data Scientist (AI Engineer, ML Engineer)",Deliveree On-Demand Logistics,NaN,None,2024-08-23,None,...,NaN,None,None,None,None,None,None,None,None,None
11,1009416907023,glassdoor,https://www.glassdoor.ca/job-listing/j?jl=1009...,None,Field Service Engineer,Onto Innovation,NaN,None,2024-08-23,None,...,NaN,None,None,None,None,None,None,None,None,None
4,1009413872036,glassdoor,https://www.glassdoor.ca/job-listing/j?jl=1009...,None,Senior Data Engineer,HSC,NaN,None,2024-08-21,None,...,NaN,None,None,None,None,None,None,None,None,None
16,1009414114841,glassdoor,https://www.glassdoor.ca/job-listing/j?jl=1009...,None,SX_AI Engineer Intern,Bosch Group,NaN,None,2024-08-21,None,...,NaN,None,None,None,None,None,None,None,None,None
17,1009413667511,glassdoor,https://www.glassdoor.ca/job-listing/j?jl=1009...,None,Engineer- Manufacturing II VNM,First Solar,NaN,None,2024-08-21,None,...,NaN,None,None,None,None,None,None,None,None,None
8,1009412464218,glassdoor,https://www.glassdoor.ca/job-listing/j?jl=1009...,None,AI ENGINEER,FPT,NaN,None,2024-08-20,None,...,NaN,None,None,None,None,None,None,None,None,None
12,1009411759348,glassdoor,https://www.glassdoor.ca/job-listing/j?jl=1009...,None,Operation Engineer,TechX Corporation,NaN,None,2024-08-20,None,...,NaN,None,None,None,None,None,None,None,None,None
15,1009410452156,glassdoor,https://www.glassdoor.ca/job-listing/j?jl=1009...,None,DATA ENGINEER,Công Ty Cổ Phần Viễn Thông FPT Telecom,NaN,None,2024-08-19,None,...,NaN,None,None,None,None,None,None,None,None,None
1,1009408051012,glassdoor,https://www.glassdoor.ca/job-listing/j?jl=1009...,None,[Bosch R&D] - Data Engineer Intern,Bosch Group,NaN,None,2024-08-16,None,...,NaN,None,None,None,None,None,None,None,None,None
14,1009408527332,glassdoor,https://www.glassdoor.ca/job-listing/j?jl=1009...,None,Data Scientist Engineer,AhaMove,NaN,None,2024-08-16,None,...,NaN,None,None,None,None,None,None,None,None,None
5,1009407037291,glassdoor,https://www.glassdoor.ca/job-listing/j?jl=1009...,None,Synthesis and Timing engineer,Synopsys,NaN,None,2024-08-15,None,...,NaN,None,None,None,None,None,None,None,None,None
13,1009407037303,glassdoor,https://www.glassdoor.ca/job-listing/j?jl=1009...,None,DFT engineer staff level,Synopsys,NaN,None,2024-08-15,None,...,NaN,None,None,None,None,None,None,None,None,None
19,1009407037292,glassdoor,https://www.glassdoor.ca/job-listing/j?jl=1009...,None,Analog Circuit Design Engineer,Synopsys,NaN,None,2024-08-15,None,...,NaN,None,None,None,None,None,None,None,None,None
3,1009404852538,glassdoor,https://www.glassdoor.ca/job-listing/j?jl=1009...,None,Dong Nai - Data Engineer (Junior),amaris,NaN,None,2024-08-13,None,...,NaN,None,None,None,None,None,None,None,None,None
6,1009404852484,glassdoor,https://www.glassdoor.ca/job-listing/j?jl=1009...,None,Hanoi/HCMC - Data Engineer (Senior),amaris,NaN,None,2024-08-13,None,...,NaN,None,None,None,None,None,None,None,None,None
7,1009404833288,glassdoor,https://www.glassdoor.ca/job-listing/j?jl=1009...,None,Dong Nai - Data Engineer (Junior),Amaris Consulting,NaN,None,2024-08-13,None,...,NaN,None,None,None,None,None,None,None,None,None
28,4007713645,linkedin,https://www.linkedin.com/jobs/view/4007713645,None,Data Engineer,Jardine Restaurant Group of Vietnam (JRGVN),"Ho Chi Minh City, Vietnam",None,2024-08-25,None,...,https://vn.linkedin.com/company/jrgvn,None,None,None,None,None,None,None,None,None
21,4006204555,linkedin,https://www.linkedin.com/jobs/view/4006204555,None,Data Engineer,Grab,"Quận 7, Ho Chi Minh City, Vietnam",None,2024-08-23,None,...,https://sg.linkedin.com/company/grabapp,None,None,None,None,None,None,None,None,None
27,4004746273,linkedin,https://www.linkedin.com/jobs/view/4004746273,None,Data Engineer,Kyanon Digital,"Ho Chi Minh City, Vietnam",None,2024-08-23,None,...,https://vn.linkedin.com/company/kyanon,None,None,None,None,None,None,None,None,None
39,4008287231,linkedin,https://www.linkedin.com/jobs/view/4008287231,None,Data Analyst,Sky Mavis,"Ho Chi Minh City, Ho Chi Minh City, Vietnam",None,2024-08-23,None,...,https://sg.linkedin.com/company/skymavis,None,None,None,None,None,None,None,None,None
30,4004729455,linkedin,https://www.linkedin.com/jobs/view/4004729455,None,Data Engineer,FPT Software,"Ho Chi Minh City, Vietnam",None,2024-08-22,None,...,https://vn.linkedin.com/company/fpt-software,None,None,None,None,None,None,None,None,None
22,4007053051,linkedin,https://www.linkedin.com/jobs/view/4007053051,None,Data Engineer,Renn Labs,"Ho Chi Minh City, Ho Chi Minh City, Vietnam",None,2024-08-21,None,...,https://www.linkedin.com/company/renn-labs,None,None,None,None,None,None,None,None,None
37,4003643390,linkedin,https://www.linkedin.com/jobs/view/4003643390,None,Data Engineer,Insight Data,,None,2024-08-21,None,...,https://vn.linkedin.com/company/insight-data-vn,None,None,None,None,None,None,None,None,None
33,3987093509,linkedin,https://www.linkedin.com/jobs/view/3987093509,None,Production Data Analyst,the LEGO Group,"Bac Tan Uyen, Binh Duong, Vietnam",None,2024-08-20,None,...,https://dk.linkedin.com/company/lego-group,None,None,None,None,None,None,None,None,None
38,4002688468,linkedin,https://www.linkedin.com/jobs/view/4002688468,None,Data Platform Engineer,MBBank,,None,2024-08-20,None,...,https://vn.linkedin.com/company/mbbank,None,None,None,None,None,None,None,None,None
25,4000222135,linkedin,https://www.linkedin.com/jobs/view/4000222135,None,Data Engineer,TechX Corp.,"Quận Cầu Giấy, Hanoi, Vietnam",None,2024-08-16,None,...,https://vn.linkedin.com/company/techx-corporation,None,None,None,None,None,None,None,None,None
29,3998221793,linkedin,https://www.linkedin.com/jobs/view/3998221793,None,Data Engineer,VMO Holdings,,None,2024-08-14,None,...,https://vn.linkedin.com/company/vmogroup,None,None,None,None,None,None,None,None,None
34,3998002674,linkedin,https://www.linkedin.com/jobs/view/3998002674,None,Data Engineer,Synodus,"Hanoi, Hanoi, Vietnam",None,2024-08-14,None,...,https://vn.linkedin.com/company/synodusofficial,None,None,None,None,None,None,None,None,None
20,3997523028,linkedin,https://www.linkedin.com/jobs/view/3997523028,None,Dong Nai - Data Engineer (Junior),Amaris Consulting,"Ho Chi Minh City, Ho Chi Minh City, Vietnam",None,2024-08-13,None,...,https://ch.linkedin.com/company/amaris,None,None,None,None,None,None,None,None,None
24,4000353131,linkedin,https://www.linkedin.com/jobs/view/4000353131,None,Dong Nai - Data Engineer (Junior),Amaris Consulting,,None,2024-08-13,None,...,https://ch.linkedin.com/company/amaris,None,None,None,None,None,None,None,None,None
32,3996929486,linkedin,https://www.linkedin.com/jobs/view/3996929486,None,Data Engineer,Evotek,,None,2024-08-13,None,...,https://vn.linkedin.com/company/evotekvn,None,None,None,None,None,None,None,None,None
35,3997208558,linkedin,https://www.linkedin.com/jobs/view/3997208558,None,Data Operation Engineer,Renesas Electronics,,None,2024-08-13,None,...,https://jp.linkedin.com/company/renesas,None,None,None,None,None,None,None,None,None
36,3974443932,linkedin,https://www.linkedin.com/jobs/view/3974443932,None,Data Engineer (Only Banking Industry),LPBank,,None,2024-08-13,None,...,https://vn.linkedin.com/company/lpbank,None,None,None,None,None,None,None,None,None
23,4007747512,linkedin,https://www.linkedin.com/jobs/view/4007747512,None,Data Engineer (Around 1500$),KiotViet,"Hanoi, Hanoi, Vietnam",None,NaN,None,...,https://vn.linkedin.com/company/kiotviet,None,None,None,None,None,None,None,None,None
26,4010306625,linkedin,https://www.linkedin.com/jobs/view/4010306625,None,Reporting Analytics Engineer,Renesas Electronics,,None,NaN,None,...,https://jp.linkedin.com/company/renesas,None,None,None,None,None,None,None,None,None
31,4007790794,linkedin,https://www.linkedin.com/jobs/view/4007790794,None,Senior Data Engineer,TechX Corp.,,None,NaN,None,...,https://vn.linkedin.com/company/techx-corporation,None,None,None,None,None,None,None,None,None

In [46]:
jobs["location"] = jobs["location"].fillna("")

In [47]:
jobs["location"].value_counts()

location
                                               29
Ho Chi Minh City, Vietnam                       3
Ho Chi Minh City, Ho Chi Minh City, Vietnam     3
Hanoi, Hanoi, Vietnam                           2
Quận 7, Ho Chi Minh City, Vietnam               1
Bac Tan Uyen, Binh Duong, Vietnam               1
Quận Cầu Giấy, Hanoi, Vietnam                   1
Name: count, dtype: int64

In [41]:
import re
import hashlib

def clean_text(text):
    return re.sub("[^a-zA-Z]", "", text).lower()

def hash_text_md5(text):
    return hashlib.md5(text.encode()).hexdigest()

jobs["hashId"] = jobs.apply(lambda x: hash_text_md5(clean_text(x["title"] + x["company"])), axis=1)

In [42]:
jobs[jobs["hashId"] == "1c10d9827c1f1e338731f9a2597863fb"]

Empty DataFrame
Columns: [id, site, job_url, job_url_direct, title, company, location, job_type, date_posted, salary_source, interval, min_amount, max_amount, currency, is_remote, job_level, job_function, company_industry, listing_type, emails, description, company_url, company_url_direct, company_addresses, company_num_employees, company_revenue, company_description, logo_photo_url, banner_photo_url, ceo_name, ceo_photo_url, hashId]
Index: []

[0 rows x 32 columns]

In [49]:
jobs.company.value_counts().sort_index()

company
AhaMove                                           1
Amaris Consulting                                 3
Bosch Group                                       2
Công Ty Cổ Phần Viễn Thông FPT Telecom            1
Deliveree On-Demand Logistics                     1
Deliveree On-Demand Logistics (Southeast Asia)    1
Evotek                                            1
FPT                                               1
FPT Software                                      1
First Solar                                       1
Google                                            1
Grab                                              1
HSC                                               1
Insight Data                                      1
Jardine Restaurant Group of Vietnam (JRGVN)       1
KMS Technology                                    1
KiotViet                                          1
Kyanon Digital                                    1
LPBank                                            1
MBBank                                            1
Onto Innovation                                   1
Renesas Electronics                               2
Renn Labs                                         1
Sky Mavis                                         1
Synodus                                           1
Synopsys                                          3
TechX Corp.                                       2
TechX Corporation                                 1
VMO Holdings                                      1
VNG                                               1
amaris                                            2
the LEGO Group                                    1
Name: count, dtype: int64

In [50]:
jobs[jobs["company"] == "Bosch Group"]

,id,site,job_url,job_url_direct,title,company,location,job_type,date_posted,salary_source,...,company_url,company_url_direct,company_addresses,company_num_employees,company_revenue,company_description,logo_photo_url,banner_photo_url,ceo_name,ceo_photo_url
16,1009414114841,glassdoor,https://www.glassdoor.ca/job-listing/j?jl=1009...,None,SX_AI Engineer Intern,Bosch Group,,None,2024-08-21,None,...,NaN,None,None,None,None,None,None,None,None,None
1,1009408051012,glassdoor,https://www.glassdoor.ca/job-listing/j?jl=1009...,None,[Bosch R&D] - Data Engineer Intern,Bosch Group,,None,2024-08-16,None,...,NaN,None,None,None,None,None,None,None,None,None

In [33]:
jobs.head(5)

,id,site,job_url,job_url_direct,title,company,location,job_type,date_posted,salary_source,...,company_url_direct,company_addresses,company_num_employees,company_revenue,company_description,logo_photo_url,banner_photo_url,ceo_name,ceo_photo_url,hashId
8,1009418616786,glassdoor,https://www.glassdoor.ca/job-listing/j?jl=1009...,None,"Data Engineer , Stores FinTech",Amazon Development Centre Canada ULC,Toronto,None,2024-08-25,direct_data,...,None,None,None,None,None,https://media.glassdoor.com/sql/6036/amazon-sq...,None,None,None,4e3d5399b154e9071ee86720e5c5f0ab
3,1009418009668,glassdoor,https://www.glassdoor.ca/job-listing/j?jl=1009...,None,Data Scientist / Engineer (Toronto-Hybrid),Shift Technology,Toronto,None,2024-08-24,direct_data,...,None,None,None,None,None,https://media.glassdoor.com/sql/1369971/shift-...,None,None,None,c0c2af773f9666bdc5b0842dfb45dc75
12,1009417941861,glassdoor,https://www.glassdoor.ca/job-listing/j?jl=1009...,None,Data Engineer,CGI,Markham,None,2024-08-24,direct_data,...,None,None,None,None,None,https://media.glassdoor.com/sql/8452/cgi-squar...,None,None,None,eaf55a923698c4e18774dafa7352dd6e
13,1009418074242,glassdoor,https://www.glassdoor.ca/job-listing/j?jl=1009...,None,GCP Data Engineer,Atlantis IT group,Toronto,None,2024-08-24,direct_data,...,None,None,None,None,None,https://media.glassdoor.com/sql/1602162/atlant...,None,None,None,177d0cad3092c3ce44705addf59c057f
1,1009416500311,glassdoor,https://www.glassdoor.ca/job-listing/j?jl=1009...,None,Data & Analytics - Analytics Engineer,Aritzia,Vancouver,None,2024-08-23,direct_data,...,None,None,None,None,None,https://media.glassdoor.com/sql/149390/aritzia...,None,None,None,a17cc4502056e427a3405bf578b0d75f

In [31]:
import re
import hashlib

# Replace non-alphabet with nothing
def clean_text(text):
    return re.sub("[^a-zA-Z]", "", text)


hashlib.md5(clean_text("123abc!@#$%^&*() !").encode()).hexdigest()

'900150983cd24fb0d6963f7d28e17f72'